### ISSUE TITLE
[Question] A better way to verify a high-level function was called?

### ISSUE THREAD

**Issue by f-person** [felangel/mocktail#106]
I needed to verify a function which was not a method in a class.

I originally wrote this:
```dart
class MockDateChanged extends Mock implements DateChanged {
  void call(DateTime date);
}
```

But, when trying to verify it was called, an `Used on a non-mocktail object` error occurred.

To fix that I made an abstract class from it and created a mock class which extends it:
```dart
abstract class DateChanged {
  void call(DateTime date);
}

class MockDateChanged extends Mock implements DateChanged {}
```

However, it would be better if there was a way to stub top-level functions without having to create 2 classes. 
Is is currently possible? And, if no, is there a way to make it possible?

**Comment by mousedownmike** [comment]
I ran into a similar issue with the `availableCameras()` function from the Flutter Camera package.  That lead me to this Stack Overflow response using **Mockito**: https://stackoverflow.com/a/57582785/11892360

I confirmed that the approach **does work with Mocktail** but you still have to be passing the function into the calling Class or Function in order to be able to have your Mock called. 

This would have been the only function I was handling this way so I ended up doing what you're doing and wrapped the call to `availableCameras()` into a class that I then mock and inject into my service/repository/bloc...

**Comment by mousedownmike** [comment]
Looking in my history, it looks like this is what I had before I changed direction:

```dart
class MockAvailableCameras extends Mock {
  Future<List<CameraDescription>> call();
}
void main() {
  group('Scanner', () {
    late Future<List<CameraDescription>> Function() availableCameras;
    late Scanner scanner;
    const available = <CameraDescription>[
      CameraDescription(name: 'back', lensDirection: CameraLensDirection.back, sensorOrientation: 0),
      CameraDescription(name: 'front', lensDirection: CameraLensDirection.front, sensorOrientation: 0),
      CameraDescription(name: 'external', lensDirection: CameraLensDirection.external, sensorOrientation: 0)
    ];
    setUp(() {
      availableCameras = MockAvailableCameras()
      scanner = const Scanner(availableCameras: availableCameras);
    });
    group('get camera', () {
      test('success defaults', () async {
        when(() => availableCameras()).thenAnswer((_) async {
          return available;
        });
        var camera = await scanner.camera;
        expect(camera, isNotNull);
        expect(camera.description, available[0]);
        expect(camera.resolutionPreset, ResolutionPreset.high);
        expect(camera.enableAudio, false);
      });
    });
  });
}
```

**Comment by f-person** [comment]
@mousedownmike thank you! Didn't think about making the `call` method abstract. This works fine now:

```dart
class MockDateChanged extends Mock {
  void call(DateTime date);
}
```
