### ISSUE TITLE
Partial mock

### ISSUE THREAD

**Issue by dan-leech** [felangel/mocktail#38]
I'm not sure that it's possible in Dart, but it would be nice to have partial mock.

What it means:
You have a mocked class with methods. 
Any method works as in a real class instance until you apply 'when' to the method.

**Comment by felangel** [comment]
Hi @dan-leech 👋 
Thanks for opening an issue!

As far as I know, I don't think this would be possible with the current approach because `when` works by relying on `noSuchMethod` which would not be triggered if there was a real method which could be invoked in the first place. 

I also think this would be confusing because it wouldn't be obvious which methods are stubs and which are real. In my opinion, when I see a `Mock` I automatically assume that all implementations are stubbed.

Is there a mocking library which supports this functionality as a reference? Thanks!

**Comment by dan-leech** [comment]
@felangel You are right this is not good practice to use this, but btw https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#16

**Comment by felangel** [comment]
Thanks for providing the link. Closing this for now since I'd prefer to avoid introducing support for this based on our discussion and we can revisit this topic at a later time if needed 👍

**Comment by R4dix** [comment]
I think this feature would be great and it could be implemented like this:
`MockClass extends PartialMock implements Class`
What do you think?
