### ISSUE TITLE
Operator == implementation must use dynamic instead of Object type

### ISSUE THREAD

**Issue by GiteshDalal** [felangel/mocktail#39]
https://github.com/felangel/mocktail/blob/1d09cb2898dc9a6b27f82c1962515308bb7afa5d/packages/mocktail/lib/src/mocktail.dart#L140

`bool operator ==(dynamic other) => identical(this, other);`

In some cases Object doesnt work.
Example -
`Mock.==' ('bool Function(Object)')` isn't a valid override of `'GoogleSignInAccount.==' ('bool Function(dynamic)').`

**Comment by felangel** [comment]
Hi @GiteshDalal 👋 
Thanks for opening an issue!

This should be updated in the underlying project because we should prefer to use `Object` in favor of `dynamic` when overriding `==`.

For now, you can use a mixin to address this issue:

```dart
mixin LegacyEquality {
  @override
  bool operator ==(dynamic other) => throw UnimplementedError();

  @override
  int get hashCode => throw UnimplementedError();
}
```

Then you can mixin this is when defining a mock instance:

```dart
class MockGoogleSignInAccount extends Mock with LegacyEquality implements GoogleSignInAccount {}
```

Hope that helps 👍

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍
