### ISSUE TITLE
[question] function as parameter

### ISSUE THREAD

**Issue by Chaitanyabsprip** [felangel/mocktail#93]
how can I verify that the function passed as a parameter to the SUT method is called?
I have tried the following approach but i get `Used on a non-mocktail object` error

```dart
class MockParameterFunction extends Mock {
    void call(int statusCode) {}
}

test('should call parameterFunction when it is not null', () async {
    const tParam = 400;
    mockParameterFunction = MockParameterFunction();
    when(() => mockClass.method(any())).thenAnswer(
        (_) async => returnValue,
    );
    expect(
        () => sut.get('', parameterFunction: mockParameterFunction),
        throwsA(isA<Exception>()),
    );
    verify(() => mockErrorCallback(tParam));
});
```

**Comment by felangel** [comment]
Hi @Chaitanyabsprip 👋 
Thanks for opening an issue!

This is working as expected because you are mocking the class and stubbing the `method` which means that the function being passed as a parameter won't actually be called. You generally should only mock the dependencies of the thing you're testing. In this case `mockClass` should be real and you can inject a mock parameter function into the real instance to make sure it is being invoked.

If you're still having trouble, please provide a link to a minimal reproduction sample so that we're able to reproduce the issue locally, thanks!

Hope that helps 👍
